In [2]:
import pandas as pd
import numpy as np

Question 1

Create a 3x3x3 array with random values

In [53]:
import numpy as np
arr=np.random.randint(1,100,size=(3,3))
arr1=np.random.randint(101,200,size=(3,3))
arr2=np.random.randint(201,300,size=(3,3))
print(arr)
print("\n",arr1)
print("\n",arr2)

[[60  4 10]
 [10 22 57]
 [95 47 14]]

 [[155 154 179]
 [127 105 191]
 [179 148 188]]

 [[250 239 265]
 [271 206 281]
 [263 226 257]]


Question 2

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [54]:
import numpy as np
z=np.zeros((5,5),dtype=int)
arr=np.array(z)
arr[1][0]=1
arr[2][1]=2
arr[3][2]=3
arr[4][3]=4
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Question 3

Create a 8x8 matrix and fill it with a checkerboard pattern

In [55]:
import numpy as np
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Question 4

Normalize a 5x5 random matrix

In [56]:
import numpy as np
arr=np.random.random((5,5))
min=arr.min()
max=arr.max()
arr=(arr-min)/(max-min)
print(arr)

[[0.02484968 0.9139571  0.45530056 0.98260142 0.86428753]
 [0.02963238 0.47358223 0.59542821 0.88910528 0.53414664]
 [0.62513919 0.25967702 0.95463748 0.51956064 0.5883396 ]
 [1.         0.28766963 0.57754853 0.99288215 0.7212975 ]
 [0.74953627 0.01280082 0.35147947 0.2067764  0.        ]]


Question 5

How to find common values between two arrays?

In [57]:
import numpy as np
arr=np.array([1,2,4,5,14,26,23])
arr1=np.array([4,1,6,2,67,95,14])
print(arr)
print("\n",arr1)
print("\n Commom values \n",np.intersect1d(arr,arr1))

[ 1  2  4  5 14 26 23]

 [ 4  1  6  2 67 95 14]

 Commom values 
 [ 1  2  4 14]


Question 6

How to get the dates of yesterday, today and tomorrow?

In [59]:
import numpy as np
Today=np.datetime64("Today","D")
Tomorrow=np.datetime64("Today","D")+np.timedelta64(1,"D")
Yesterday=np.datetime64("Today","D")-np.timedelta64(1,"D")
print("Today:",Today)
print("Tomorrow:",Tomorrow)
print("Yesterday:",Yesterday)

Today: 2020-07-26
Tomorrow: 2020-07-27
Yesterday: 2020-07-25


Question 7

Consider two random array A and B, check if they are equal

In [60]:
import numpy as np
Array_A=np.random.random((3,3))
Array_B=np.random.random((3,3))
print(Array_A)
print(Array_B)
Equal=np.allclose(Array_A,Array_B)
if Equal==False:
    print("Array's are not Equal ")
else:
    print("Array's are Equal ")

[[0.27786251 0.15713884 0.95029077]
 [0.95234214 0.23392006 0.57959458]
 [0.16494856 0.14374381 0.46351319]]
[[0.48198839 0.18141117 0.92019017]
 [0.9915869  0.08658747 0.2942602 ]
 [0.19496694 0.23991933 0.37385305]]
Array's are not Equal 


Question 8

create random vector of size 10 and replace the maximum value by 0

In [61]:
import numpy as np
x=np.random.random(10)
vec=np.array(x)
print(vec)
vec[vec.argmax()]=int(0)
print(vec)

[0.52743186 0.85552055 0.92114763 0.37417786 0.94394256 0.92941676
 0.9955701  0.20989433 0.39389641 0.28676814]
[0.52743186 0.85552055 0.92114763 0.37417786 0.94394256 0.92941676
 0.         0.20989433 0.39389641 0.28676814]


Question 9

How to print all the values of an array?

In [62]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


Question 10

Subtract the mean of each row of a matrix

In [31]:
import numpy as np
arr=np.array([[98,34,56],[84,65,23]])
print(arr)
x=arr.mean(axis=1,keepdims=True)
print(arr-x)

[[98 34 56]
 [84 65 23]]
[[ 35.33333333 -28.66666667  -6.66666667]
 [ 26.66666667   7.66666667 -34.33333333]]


Question 11

Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [63]:
import numpy as np
arr=np.ones(10,dtype=int)
rand=np.random.randint(0,len(arr),15)
np.add.at(arr,rand,1)
print(arr)

[2 2 2 3 2 2 3 3 4 2]


Question 12

How to get the diagonal of a dot product?

In [64]:
import numpy as np
arr=np.array([[1,2],[3,4]])
arr1=np.array([[5,6],[7,8]])
dot=arr.dot(arr1)
diag=np.diag(dot)
print(diag)

[19 50]


Question 13

How to find the most frequent value in an array?

In [65]:
import numpy as np
arr=np.array([33,54,65,234,653,324,56,54,9,399,24,54,33,234,53,64,54])
most=np.bincount(arr).argmax()
print(most)

54


Question 14

How to get the n largest values of an array

In [46]:
#This qustion was a bit hard so i searched for it on internet and got something similar to below program

In [66]:
import numpy as np
arr=np.arange(1000)
np.random.shuffle(arr)
no=4
print(arr[np.argsort(arr)[-no:]])


[996 997 998 999]


Question 15

How to create a record array from a regular array?

In [67]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
record=np.core.records.fromarrays(arr.T)
print(record)

[[1 2 3 4]
 [5 6 7 8]]
[(1, 2, 3, 4) (5, 6, 7, 8)]
